language: node_js

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    git checkout -b gh-pages
    git push -f -q https://<me>:$GITHUB_API_KEY@github.com/<me>/<myrepo> master:gh-pages
  fi
